openapi: 3.1.0

info:
  title: Provar.se API
  version: 1.0.0

servers:
  - url: http://localhost:3001
  - url: https://api.provar.se

paths:
  /ping:
    get:
      summary: Basic healthcheck
      responses:
        200:
          description: Healthcheck success response
  /organization/{organizationID}/feedback:
    post:
      summary: Store user feedback
      parameters:
        - name: organizationID
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Feedback created successfully
