// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1, arg2) {
  return window['go']['bindings']['Doctor']['Emit'](arg1, arg2);
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['Doctor']['LogErrorf'](arg1, arg2);
}

export function RunChecks(arg1) {
  return window['go']['bindings']['Doctor']['RunChecks'](arg1);
}
