// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function Emit(arg1:string,arg2:Array<any>):Promise<void>;

export function LogErrorf(arg1:string,arg2:Array<any>):Promise<void>;

export function RunChecks(arg1:string):Promise<Array<bindings.DoctorCheck>>;
