// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['bindings']['Run']['Cancel'](arg1);
}

export function Emit(arg1, arg2) {
  return window['go']['bindings']['Run']['Emit'](arg1, arg2);
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['Run']['LogErrorf'](arg1, arg2);
}

export function Start(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['Run']['Start'](arg1, arg2, arg3, arg4);
}
