// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1, arg2) {
  return window['go']['bindings']['Watcher']['Emit'](arg1, arg2);
}

export function LogErrorf(arg1, arg2) {
  return window['go']['bindings']['Watcher']['LogErrorf'](arg1, arg2);
}

export function Watch(arg1) {
  return window['go']['bindings']['Watcher']['Watch'](arg1);
}
