# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # The yarn mono repository
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Web API written in Go
  - package-ecosystem: "gomod"
    directory: "/apps/webapi"
    schedule:
      interval: "weekly"

  # Github actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
