services:
  # MongoDB is used to store customer feedback
  mongodb:
    image: mongo:7
    restart: always
    volumes:
      - database:/data/db
    ports:
      - 27017:27017

  # Use Jackson to manage user accounts and SSO
  accounts:
    image: boxyhq/jackson
    restart: always
    ports:
      - 5225:5225
    env_file:
      - apps/account/.env

volumes:
  database: {}
