services:
  # PostgreSQL is used to store customer feedback
  postgresql:
    image: postgres:16-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: provar

  # Use mailpit to test emails when developing
  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database: {}
