# Stage 1: Build Caddy with Cloudflare module
FROM caddy:2.9.1-builder-alpine AS builder
RUN xcaddy build --with github.com/caddy-dns/cloudflare

# Stage 2: Create the final caddy docker image
FROM caddy:2.9.1-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
ENTRYPOINT ["caddy"]
CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
