openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /auth/email/confirm:
    post:
      operationId: EmailAuthentication_confirm
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
  /auth/email/prepare:
    post:
      operationId: EmailAuthentication_prepare
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
  /auth/whoami:
    get:
      operationId: Authentication_whoami
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      security:
        - BearerAuth: []
  /organization:
    post:
      operationId: Organization_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDetails'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                slug:
                  type: string
              required:
                - name
                - slug
      security:
        - BearerAuth: []
  /ping:
    get:
      operationId: HealthCheck_basic
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /ping/secure:
    get:
      operationId: HealthCheck_secure
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      security:
        - BearerAuth: []
components:
  schemas:
    OrganizationDetails:
      type: object
      required:
        - id
        - name
        - slug
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
