// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject():Promise<void>;

export function CompileProject():Promise<void>;

export function OpenProject():Promise<void>;

export function OpenSettingsModal():Promise<void>;

export function ProjectOpen():Promise<boolean>;

export function RunActiveTest():Promise<void>;

export function SetProjectOpen(arg1:boolean):Promise<void>;

export function ToggleConsole():Promise<void>;

export function ToggleTestExplorer():Promise<void>;
