// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject() {
  return window['go']['main']['App']['CloseProject']();
}

export function CompileProject() {
  return window['go']['main']['App']['CompileProject']();
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function OpenSettingsModal() {
  return window['go']['main']['App']['OpenSettingsModal']();
}

export function ProjectOpen() {
  return window['go']['main']['App']['ProjectOpen']();
}

export function RunActiveTest() {
  return window['go']['main']['App']['RunActiveTest']();
}

export function SetProjectOpen(arg1) {
  return window['go']['main']['App']['SetProjectOpen'](arg1);
}

export function ToggleTestExplorer() {
  return window['go']['main']['App']['ToggleTestExplorer']();
}
