openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /auth/email/confirm:
    post:
      operationId: EmailAuthentication_confirm
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
  /auth/email/prepare:
    post:
      operationId: EmailAuthentication_prepare
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
  /auth/whoami:
    get:
      operationId: Authentication_whoami
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - user
                      - credential
                  user:
                    $ref: '#/components/schemas/UserDetails'
                  credential:
                    $ref: '#/components/schemas/CredentialDetails'
                required:
                  - type
      security:
        - BearerAuth: []
  /organization:
    post:
      operationId: Organization_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDetails'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                slug:
                  type: string
                description:
                  type: string
              required:
                - name
                - slug
                - description
      security:
        - BearerAuth: []
  /organization/list:
    get:
      operationId: Organization_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationDetails'
      security:
        - BearerAuth: []
  /organization/{id}/credential/list:
    get:
      operationId: Organization_credentials
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CredentialDetails'
      security:
        - BearerAuth: []
  /organization/{id}/details:
    get:
      operationId: Organization_details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDetails'
      security:
        - BearerAuth: []
    patch:
      operationId: Organization_updateDetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                slug:
                  type: string
                description:
                  type: string
      security:
        - BearerAuth: []
  /organization/{id}/member/list:
    get:
      operationId: Organization_members
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetails'
      security:
        - BearerAuth: []
  /organization/{id}/settings:
    get:
      operationId: Organization_settings
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
      security:
        - BearerAuth: []
  /ping:
    get:
      operationId: HealthCheck_basic
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
  /ping/secure:
    get:
      operationId: HealthCheck_secure
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      security:
        - BearerAuth: []
components:
  schemas:
    CredentialDetails:
      type: object
      required:
        - id
        - createdAt
        - modifiedAt
        - lastUsedAt
        - organizationId
        - name
        - secret
      properties:
        id:
          type: string
        createdAt:
          type: string
        modifiedAt:
          type: string
        lastUsedAt:
          type: string
        organizationId:
          type: string
        name:
          type: string
        secret:
          type: string
    OrganizationDetails:
      type: object
      required:
        - id
        - createdAt
        - createdBy
        - modifiedAt
        - name
        - slug
        - description
      properties:
        id:
          type: string
        createdAt:
          type: string
        createdBy:
          type: string
        modifiedAt:
          type: string
        name:
          type: string
        slug:
          type: string
        description:
          type: string
    UserDetails:
      type: object
      required:
        - id
        - createdAt
        - modifiedAt
        - avatar
        - email
        - name
      properties:
        id:
          type: string
        createdAt:
          type: string
        modifiedAt:
          type: string
        avatar:
          type: string
        email:
          type: string
        emailVerifiedAt:
          type: string
        name:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
