// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/organization/{organization_id}/feedback": {
            "post": {
                "description": "Creates a new feedback for the organization.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "feedback"
                ],
                "summary": "Creates a new feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organization_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "ok"
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Basic healthcheck endpoint that can be used to check whether the service can be reached.",
                "tags": [
                    "health"
                ],
                "summary": "Basic healthcheck endpoint",
                "responses": {
                    "204": {
                        "description": "ok"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://api.provar.se",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Provar API",
	Description:      "Provar.se public API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
