info:
  contact: {}
paths:
  /feedback:
    post:
      consumes:
      - application/json
      description: Create a new feedback event for an organization.
      responses:
        "204":
          description: ok
      summary: Create a new feedback event for an organization.
      tags:
      - feedback
  /ping:
    get:
      description: Ensure that the service can be reached.
      responses:
        "204":
          description: ok
      summary: Ensure that the service can be reached.
      tags:
      - health
  /ping/secure:
    get:
      description: Ensure that the api key is valid
      responses:
        "204":
          description: ok
      summary: Ensure that the api key is valid
      tags:
      - health
swagger: "2.0"
