definitions:
  auth.CreateAccessTokenResponseBody:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/token:
    post:
      consumes:
      - application/json
      description: Create an access token using client credentials.
      parameters:
      - description: Organization ID
        in: path
        name: x-organization
        type: string
      - description: Key
        in: body
        name: key
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.CreateAccessTokenResponseBody'
      summary: Create an access token using client credentials.
      tags:
      - auth
  /feedback:
    post:
      consumes:
      - application/json
      description: Create a new feedback event for an organization.
      parameters:
      - description: Organization ID
        in: path
        name: x-organization
        type: string
      responses:
        "204":
          description: ok
      summary: Create a new feedback event for an organization.
      tags:
      - feedback
  /ping:
    get:
      description: Ensure that the service can be reached.
      responses:
        "204":
          description: ok
      summary: Ensure that the service can be reached.
      tags:
      - health
  /ping/secure:
    get:
      description: Ensure that an access token is valid.
      responses:
        "204":
          description: ok
      summary: Ensure that an access token is valid.
      tags:
      - health
swagger: "2.0"
