definitions:
  feedback.RequestBody:
    properties:
      data:
        $ref: '#/definitions/repository.FeedbackData'
      type:
        $ref: '#/definitions/repository.FeedbackType'
    type: object
  repository.FeedbackData:
    properties:
      text:
        type: string
    type: object
  repository.FeedbackType:
    enum:
    - text
    type: string
    x-enum-varnames:
    - FeedbackTypeText
info:
  contact: {}
paths:
  /feedback:
    post:
      consumes:
      - application/json
      description: Create a new feedback event for an organization.
      parameters:
      - description: The request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/feedback.RequestBody'
      responses:
        "204":
          description: ok
      summary: Create a new feedback event for an organization.
      tags:
      - feedback
  /ping:
    get:
      description: Ensure that the service can be reached.
      responses:
        "204":
          description: ok
      summary: Ensure that the service can be reached.
      tags:
      - health
  /ping/secure:
    get:
      description: Ensure that the api key is valid
      responses:
        "204":
          description: ok
      summary: Ensure that the api key is valid
      tags:
      - health
swagger: "2.0"
