# apps/webapp - quality checks

name: apps/webapp - quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/**"
      - "apps/webapp/**"

concurrency:
  group: "app.webapp.quality-checks-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    defaults:
      run:
        working-directory: ./apps/webapp

    env:
      PUBLIC_PROVAR_API_URL: "test-api-url"
      PUBLIC_PROVAR_APP_URL: "test-app-url"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Setup Yarn
        run: yarn install --silent

      - name: Build the application
        run: yarn build

      - name: Check code formatting
        run: yarn lint

      - name: Check code errors
        run: yarn check

      - name: Check unit tests
        run: yarn test:unit

      - name: Publish to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.APPS_WEBAPP_CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.APPS_WEBAPP_CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.APPS_WEBAPP_CLOUDFLARE_PROJECT_NAME }}
          directory: ./apps/webapp/.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
