# apps/webapi - deploy production

name: apps/webapi - deploy production

on:
  push:
    branches: ["main"]
    paths:
      - ".github/apps.webapi.*.yml"
      - "apps/webapi/**"
  workflow_dispatch:

concurrency:
  group: "app.webapi.deploy-production"
  cancel-in-progress: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    defaults:
      run:
        working-directory: ./apps/webapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          service_account: "${{ secrets.APPS_WEBAPI_GCP_SERVICE_ACCOUNT }}"
          credentials_json: "${{ secrets.APPS_WEBAPI_GCP_CREDENTIALS }}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "_json_key"
          password: "${{ secrets.APPS_WEBAPI_GCP_CREDENTIALS }}"
          registry: "${{ secrets.APPS_WEBAPI_GCP_GAR_REGISTRY }}"

      - name: Build docker image
        run: docker build -t "${{ secrets.APPS_WEBAPI_GCP_GAR_REPOSITORY }}/webapi:${{ github.sha }}" .

      - name: Push docker image
        run: |-
          docker push "${{ secrets.APPS_WEBAPI_GCP_GAR_REPOSITORY }}/webapi:${{ github.sha }}"

      - name: Deploy the service
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: "${{ secrets.APPS_WEBAPI_GCP_CLOUD_RUN_SERVICE }}"
          region: "${{ secrets.APPS_WEBAPI_GCP_REGION }}"
          image: "${{ secrets.APPS_WEBAPI_GCP_GAR_REPOSITORY }}/webapi:${{ github.sha }}"
          env_vars: |
            MONGO_URI=${{ secrets.APPS_WEBAPI_APP_MONGO_URI }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
