# apps/webapp - deploy production

name: apps/webapp - deploy production

on:
  push:
    branches: ["main"]
    paths:
      - ".github/apps.webapp.*.yml"
      - "apps/webapp/**"
  workflow_dispatch:

concurrency:
  group: "app.webapp.deploy-production"
  cancel-in-progress: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    defaults:
      run:
        working-directory: ./apps/webapp

    env:
      MONGODB_URL: mongodb://localhost:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Setup Yarn
        run: yarn install --silent

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          service_account: "${{ secrets.APPS_WEBAPP_GCP_SERVICE_ACCOUNT }}"
          credentials_json: "${{ secrets.APPS_WEBAPP_GCP_CREDENTIALS }}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "_json_key"
          password: "${{ secrets.APPS_WEBAPP_GCP_CREDENTIALS }}"
          registry: "${{ secrets.APPS_WEBAPP_GCP_GAR_REGISTRY }}"

      - name: Build the service
        env:
          PUBLIC_PROVAR_API_KEY: ${{ secrets.APPS_WEBAPP_APP_PROVAR_API_KEY }}
        run: yarn build

      - name: Build docker image
        run: docker build -t "${{ secrets.APPS_WEBAPP_GCP_GAR_REPOSITORY }}/webapp:${{ github.sha }}" .

      - name: Push docker image
        run: |-
          docker push "${{ secrets.APPS_WEBAPP_GCP_GAR_REPOSITORY }}/webapp:${{ github.sha }}"

      - name: Deploy the service
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: "${{ secrets.APPS_WEBAPP_GCP_CLOUD_RUN_SERVICE }}"
          region: "${{ secrets.APPS_WEBAPP_GCP_REGION }}"
          image: "${{ secrets.APPS_WEBAPP_GCP_GAR_REPOSITORY }}/webapp:${{ github.sha }}"
          env_vars: |
            AUTH_SECRET=${{ secrets.APPS_WEBAPP_APP_AUTH_SECRET }}
            AUTH_GITHUB_ID=${{ secrets.APPS_WEBAPP_APP_AUTH_GITHUB_ID }}
            AUTH_GITHUB_SECRET=${{ secrets.APPS_WEBAPP_APP_AUTH_GITHUB_SECRET }}
            AUTH_GOOGLE_ID=${{ secrets.APPS_WEBAPP_APP_AUTH_GOOGLE_ID }}
            AUTH_GOOGLE_SECRET=${{ secrets.APPS_WEBAPP_APP_AUTH_GOOGLE_SECRET }}
            AUTH_EMAIL_SERVER=${{ secrets.APPS_WEBAPP_APP_AUTH_EMAIL_SERVER }}
            AUTH_EMAIL_FROM=${{ secrets.APPS_WEBAPP_APP_AUTH_EMAIL_FROM }}
            MONGODB_URL=${{ secrets.APPS_WEBAPP_APP_MONGODB_URL }}
            ORIGIN=https://app.provar.se

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
