# apps/webapi - quality checks

name: apps/webapi - quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/**"
      - "apps/webapi/**"

concurrency:
  group: "app.webapi.quality-checks-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./apps/webapi

    env:
      MONGODB_URL: mongodb://localhost:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
          cache-dependency-path: apps/webapi/go.sum

      - name: Install dependencies
        run: yarn setup

      - name: Build the service
        run: yarn build

      - name: Check code formatting
        run: yarn lint

      - name: Check code errors
        run: yarn check

      - name: Check unit tests
        run: yarn test:unit

      - name: Check integration tests
        run: yarn test:integration
