# apps/webapi - quality checks

name: apps/webapi - quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/apps.webapi.*.yml"
      - "apps/webapi/**"

concurrency:
  group: "app.webapi.quality-checks-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./apps/webapi

    env:
      MONGO_URI: mongodb://localhost:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
          cache-dependency-path: apps/webapi/go.sum

      - name: Install dependencies
        run: go mod download

      - name: Build the service
        run: go build -o ./webapi

      - name: Check code formatting
        run: test -z "$(gofmt -l .)"

      - name: Check code errors
        run: go vet ./...

      - name: Check unit tests
        run: go test ./... -json > unit-test-results.json

      - name: Upload unit test results
        uses: actions/upload-artifact@v3
        with:
          name: Unit test results
          path: unit-test-results.json
