# apps/webapp - quality checks

name: apps/webapp - quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/**"
      - "apps/webapp/**"

concurrency:
  group: "app.webapp.quality-checks-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    defaults:
      run:
        working-directory: ./apps/webapp

    env:
      PUBLIC_PROVAR_API_URL: "test-api-url"
      PUBLIC_PROVAR_APP_URL: "test-app-url"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Setup Yarn
        run: yarn install --silent

      - name: Build the service
        run: yarn build

      - name: Check code formatting
        run: yarn lint

      - name: Check code errors
        run: yarn check

      - name: Check unit tests
        run: yarn test:unit

      - name: Install playwright
        run: yarn playwright install --with-deps

      - name: Check integration tests
        run: yarn test:integration
