# apps/webapp - deploy production

name: apps/webapp - deploy production

on:
  push:
    branches: ["main"]
    paths:
      - ".github/apps.webapp.*.yml"
      - "apps/webapp/**"
  workflow_dispatch:

concurrency:
  group: "app.webapp.deploy-production"
  cancel-in-progress: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: read
      id-token: write
      deployments: write

    defaults:
      run:
        working-directory: ./apps/webapp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Setup Yarn
        run: yarn install --silent

      - name: Build the service
        env:
          PUBLIC_PROVAR_APP_URL: ${{ secrets.APPS_WEBAPP_APP_PUBLIC_PROVAR_APP_URL }}
          PUBLIC_PROVAR_API_URL: ${{ secrets.APPS_WEBAPP_APP_PUBLIC_PROVAR_API_URL }}
        run: yarn build

      - name: Publish to Cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.APPS_WEBAPP_CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.APPS_WEBAPP_CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.APPS_WEBAPP_CLOUDFLARE_PROJECT_NAME }}
          directory: ./apps/webapp/.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
