# apps/webapi - quality checks

name: apps/webapi - quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/**"
      - "apps/webapi/**"

concurrency:
  group: "app.webapi.quality-checks-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./apps/webapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.3"
          cache-dependency-path: apps/webapi/go.sum

      - name: Install dependencies
        run: go mod download

      - name: Build the service
        run: go build -o ./webapi

      - name: Check code formatting
        run: test -z "$(gofmt -l .)"

      - name: Check code errors
        run: go vet ./...

      - name: Check unit tests
        env:
          MONGO_URI: mongodb://localhost:27017/provar-test
          JWT_SECRET: 2A1HLr9OPmxrEUbFNfE18w2s6uAGp+MaHyqxIk9UnXwW38iT5xWMHw
        run: go test ./... -p 1
