# apps/webapi - deploy production

name: apps/webapi - deploy production

on:
  push:
    branches: ["main"]
    paths:
      - ".github/apps.webapi.deploy-production.yml"
      - "apps/webapi/**"
  workflow_dispatch:

concurrency:
  group: "app.webapi.deploy-production"
  cancel-in-progress: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      deployments: write

    defaults:
      run:
        working-directory: ./apps/webapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
          cache-dependency-path: apps/webapi/go.sum

      - name: Install dependencies
        run: go mod download

      - name: Build the service
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -o ./webapi

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/aivara-se/provar.se/webapi

      - name: Publish Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./apps/webapi/Dockerfile
          context: ./apps/webapi
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
