# apps/webapi - deploy production

name: apps/webapi - deploy production

on:
  push:
    branches: ["main"]
    paths:
      - ".github/apps.webapi.deploy-production.yml"
      - "apps/webapi/**"
  workflow_dispatch:

concurrency:
  group: "app.webapi.deploy-production"
  cancel-in-progress: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    defaults:
      run:
        working-directory: ./apps/webapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/webapi

      - name: Download GeoLite2 DB
        run: |
          wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${{ secrets.APPS_WEBAPI_METAMIND_KEY }}&suffix=tar.gz" -O GeoLite2-City.tar.gz
          tar -xzf GeoLite2-City.tar.gz
          mv `find . | grep GeoLite2-City.mmdb` ./

      - name: Publish Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./apps/webapi/Dockerfile
          context: ./apps/webapi
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Deploy the service
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ secrets.APPS_WEBAPI_GCP_CLOUD_RUN_SERVICE }}"
          region: "${{ secrets.APPS_WEBAPI_GCP_REGION }}"
          image: "${{ secrets.APPS_WEBAPI_GCP_GAR_REPOSITORY }}/webapi:${{ github.sha }}"
          env_vars: |
            AUTH_GITHUB_ID=${{ secrets.APPS_WEBAPI_APP_AUTH_GITHUB_ID }}
            AUTH_GITHUB_SECRET=${{ secrets.APPS_WEBAPI_APP_AUTH_GITHUB_SECRET }}
            AUTH_GOOGLE_ID=${{ secrets.APPS_WEBAPI_APP_AUTH_GOOGLE_ID }}
            AUTH_GOOGLE_SECRET=${{ secrets.APPS_WEBAPI_APP_AUTH_GOOGLE_SECRET }}
            AUTH_SECRET=${{ secrets.APPS_WEBAPI_APP_AUTH_SECRET }}
            DATABASE_URI=${{ secrets.APPS_WEBAPI_APP_DATABASE_URI }}
            EMAIL_FROM=${{ secrets.APPS_WEBAPI_APP_EMAIL_FROM }}
            EMAIL_SERVER=${{ secrets.APPS_WEBAPI_APP_EMAIL_SERVER }}
            GEOLITE2_DB=${{ secrets.APPS_WEBAPI_APP_GEOLITE2_DB }}
            PROVAR_API_URL=${{ secrets.APPS_WEBAPI_APP_PROVAR_API_URL }}
            PROVAR_APP_URL=${{ secrets.APPS_WEBAPI_APP_PROVAR_APP_URL }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
