# apps/webapi - publish docker

name: apps/webapi - publish docker

on:
  release:
    types: [published]

concurrency:
  group: "app.webapi.publish-docker"
  cancel-in-progress: false

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      deployments: write

    defaults:
      run:
        working-directory: ./apps/webapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/aivara-se/provar.se/webapi

      - name: Publish Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/webapi/Dockerfile
          context: ./apps/webapi
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
