# apps/webapp - quality checks

name: apps/webapp - quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/apps.webapp.*.yml"
      - "apps/webapp/**"

concurrency:
  group: "app.webapp.quality-checks-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./apps/webapp

    env:
      MONGODB_URL: mongodb://localhost:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "javascript-typescript"

      - name: Setup Yarn
        run: yarn install --silent

      - name: Build the service
        run: yarn build

      - name: Check code formatting
        run: yarn lint

      - name: Check code errors
        run: yarn check

      - name: Check unit tests
        run: yarn test:unit

      - name: Install playwright
        run: yarn playwright install --with-deps

      - name: Check integration tests
        env:
          AUTH_SECRET: ${{ secrets.APPS_WEBAPP_APP_AUTH_SECRET }}
          AUTH_GITHUB_ID: ${{ secrets.APPS_WEBAPP_APP_AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET: ${{ secrets.APPS_WEBAPP_APP_AUTH_GITHUB_SECRET }}
          AUTH_GOOGLE_ID: ${{ secrets.APPS_WEBAPP_APP_AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.APPS_WEBAPP_APP_AUTH_GOOGLE_SECRET }}
          AUTH_EMAIL_SERVER: ${{ secrets.APPS_WEBAPP_APP_AUTH_EMAIL_SERVER }}
          AUTH_EMAIL_FROM: ${{ secrets.APPS_WEBAPP_APP_AUTH_EMAIL_FROM }}
        run: yarn test:integration

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:go"
