name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "_json_key"
          password: "${{ secrets.GCP_CREDENTIALS }}"
          registry: "${{ secrets.GCP_GAR_REGISTRY }}"

      - name: Build Image
        run: |-
          cd apps/webapp
          yarn build
          docker build -t "${{ secrets.GCP_GAR_REPOSITORY }}/webapp:${{ github.sha }}" .
          docker push "${{ secrets.GCP_GAR_REPOSITORY }}/webapp:${{ github.sha }}"

      - name: Deploy Service
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: "${{ secrets.GCP_CLOUD_RUN_SERVICE }}"
          region: "${{ secrets.GCP_REGION }}"
          image: "${{ secrets.GCP_GAR_REPOSITORY }}/webapp:${{ github.sha }}"
          env_vars: |
            AUTH_SECRET=${{ secrets.APP_AUTH_SECRET }}
            AUTH_GITHUB_ID=${{ secrets.APP_AUTH_GITHUB_ID }}
            AUTH_GITHUB_SECRET=${{ secrets.APP_AUTH_GITHUB_SECRET }}
            AUTH_GOOGLE_ID=${{ secrets.APP_AUTH_GOOGLE_ID }}
            AUTH_GOOGLE_SECRET=${{ secrets.APP_AUTH_GOOGLE_SECRET }}
            AUTH_EMAIL_SERVER=${{ secrets.APP_AUTH_EMAIL_SERVER }}
            AUTH_EMAIL_FROM=${{ secrets.APP_AUTH_EMAIL_FROM }}
            MONGODB_URL=${{ secrets.APP_MONGODB_URL }}
            ORIGIN=https://app.provar.se
            PORT=8080

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
