# libs/provar-js - quality checks

name: libs/provar-js - quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/lib.provar-js.*.yml"
      - "libs/provar-js/**"

concurrency:
  group: "lib.provar-js.quality-checks-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    defaults:
      run:
        working-directory: ./libs/provar-js

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "javascript-typescript"

      - name: Setup Yarn
        run: yarn install --silent

      - name: Build the library
        run: yarn build

      - name: Check code formatting
        run: yarn lint

      - name: Check code errors
        run: yarn check

      - name: Check unit tests
        run: yarn test:unit

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript-typescript"
